### ISSUE TITLE
Список

### ISSUE THREAD

**Issue by alex-grandson** [LebedevaL/-new-project#4]
https://github.com/LebedevaL/-new-project/blob/6c666691fd255b993de3460c8b6feae804b608f2/%D0%BC%D0%BE%D0%B9%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82/%D0%93%D0%B0%D0%BB%D0%BA%D0%B8%D0%BD%D0%B0/index/index.html#L71-L80

`<li>` не должны находиться вне спика `ul`/`ol`

фон для элементов списка делается не картинкой, а фоновым цветом. Если пытаться доделать, а не переделать заново - можно много костылей навтыкать, который невозможно будет поддерживать

Я бы делал это так:

![image](https://user-images.githubusercontent.com/70079537/199958138-e636857f-7c74-4fa4-aa9f-5646da2ebdf9.png)

1. нельзя фон такой одноцветный вставлять картинкой, когда можно использовать просто цвет
2. в одну строчку писать не надо элементы составные (про `li` со вложенными `p`,`img`)
3. Элементы списка в список

Вместо:

https://github.com/LebedevaL/-new-project/blob/6c666691fd255b993de3460c8b6feae804b608f2/%D0%BC%D0%BE%D0%B9%20%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82/%D0%93%D0%B0%D0%BB%D0%BA%D0%B8%D0%BD%D0%B0/index/index.html#L73

Вот так:

```html
<li class="categories_item">
    <img class="categories_icon"  src="../img/1.jpg">
    <p class="categories_description">HR Hub</p>
</li>
```

```css
.categories_item {
    background-color: #eaf3ff;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: start;
}

.categories_icon {
    height: 50px;
    width: auto;
    margin-right: 10px;
}

.categories_description {
    text-align-last: left;
}
````

Чтобы список выглядел как в макете, нужно ограничить еще ширину самого списка, но не элементов
